#ifndef SCREEN_H
#define SCREEN_H

// Enum to track the current screen state
enum Screen
{
    MAIN_MENU,
    SEARCH_SCREEN,
    ADMIN_LOGIN_SCREEN,
    POST_LOGIN_SCREEN,
    ADMIN_REGISTRATION_SCREEN,
    MODERATOR_REGISTRATION_SCREEN,
    FILE_OPTIONS_SCREEN,
    MODERATOR_LOGIN_SCREEN,
    POST_MODERATOR_SCREEN, 
    HOSPITAL_LOGIN_SCREEN,
    POST_HOSPITAL_SCREEN, 
    BLOOD_INVENTORY_SCREEN,
    ADD_BLOOD_SCREEN
};

#endif // SCREEN_H
